config/routes.rb
Trackdb::Application.routes.draw do

resources :users
resources :sessions, :only => [:new, :create, :destroy]

match '/login', :to => 'sessions#new'
match 'logout', :to => 'sessions#destroy'
match '/signup', :to => 'users#new'

match '/about', :to => 'pages#about'
match '/help', :to => 'pages#help'
match '/contact', :to => 'pages#contact'

   root :to => "pages#home"

end

app/models/user.rb
# == Schema Information
# Schema version: 20101101173124
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#
require 'digest' # required for encryption

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name,
                  :email,
                  :password,
                  :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #validates :password, :confirmation => true automatically creates virtual
  #attribute password_confirmation which is checked to be maching the password.
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 10..40 }
  validates :name, :presence => true,
                   :length => { :maximum => 32 }
  validates :email, :presence => true,
                    :uniqueness => { :case_sensitive => false },
                    :format => { :with => email_regex }
  before_save :encrypt_password

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  # Return true if the users's password matches the submitted passowrd
  def has_password?(submitted_password)
    # compare encrypted_password with the encrypted version of
    # submitted password
    encrypted_password == encrypt(submitted_password)
  end

  private

    def encrypt_password
      # create salt only for new user, not when checking if password matches
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(self.password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Login"
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "The combination of email/password you submitted is
                          unknown to us."
      @title = "Login"
      render :new
    else
      login user
      redirect_to user
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def new
    @title = "Sign up"
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      login @user
      redirect_to @user
      flash[:success] = "Welcome to the Track Database"
    else
      @title = "Sign up"
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #return logo for website
  def logo
    logo = image_tag "logo.png", :alt => "Track Database logo",
                                 :class => "round"
  end

  #return titles for pages
  def title
    base_title = "Track Database"
    if@title.nil?
    base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    current_user= user
  end

  def current_user= (user)
    @current_user = user
  end

  def current_user
    # ||= assigns user_from_remember_token to @current_user only if
    # @current_user isn't already assigned. Otherwise @current_user
    # is returned directly
    @current_user ||= user_from_remember_token
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    cookies.delete(:remember_token)
    current_user = nil
  end

  private

    def user_from_remember_token
      # * operator extracts arguments from array, e.g. *[a,b] returs a, b
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class ='round'>
    <ul>
      <li><%= link_to "About", about_path %>
      <li><%= link_to "Contact", contact_path%>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path%>
  <nav class = "round">
    <ul>
      <li><%= link_to "Home", root_path %>
      <li><%= link_to "Help", help_path %>
      <% if logged_in? %>
      <li><%= link_to "Logout", logout_path, :method => :delete %>
      <% else %>
      <li><%= link_to "Login", login_path %>
      <li><%= link_to "Sign up", signup_path%>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<%= stylesheet_link_tag 'blueprint/screen', :media => "screen"%>
<%= stylesheet_link_tag 'blueprint/print', :media => "print"%>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%=csrf_meta_tag %>
    <%= render "layouts/stylesheets" %>
  </head>
  <body>
    <div class ="container">
      <%= render "layouts/header" %>
      <% flash.each do |key, value| %>
        <div class = "flash <%= key %>">
          <%= value %>
        </div>
      <% end %>
      <section class= "round">
        <%= yield %>
      </section>
      <%= render "layouts/footer"%>
      <%  if Rails.env.development? %>
        <section class = "round devel_red">
        <%= debug(params) %>
        </section>
      <% end %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<p>written by paul</p>

app/views/pages/contact.html.erb
<p>The contact page</p>

app/views/pages/help.html.erb
<p>Sorry, no help available yet</p>

app/views/pages/home.html.erb
<p>Home of the track database</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %><%# puts error or errors%>
      prohibited to save your profile:
    </h2>
    <p>There were problems with the following fields:</p>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<table>
  <% @users.each do |user| %>
    <tr>
      <td> <%= link_to user.name, user_path(user.id)%></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<div class = "sign_up">
  <%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
    <div class = "field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class = "field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class = "field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class = "field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class = "actions">
      <%= f.submit "Sign up" %>
    </div>
   <% end %>
 </div>

app/views/users/show.html.erb
<h1>
  <%= @user.name %>
 </h1>